name: release

on: 
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up build args
      run: |
        echo "MAJOR_VERSION=${GITHUB_REF_NAME%%.*}" >> $GITHUB_ENV
        echo "MINOR_VERSION=${GITHUB_REF_NAME%.*}" >> $GITHUB_ENV
        echo "BUILD_VERSION=${GITHUB_REF_NAME%-*}" >> $GITHUB_ENV
        echo "TAG_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          frosty5689/mdc:${{ env.MAJOR_VERSION }}
          frosty5689/mdc:${{ env.MINOR_VERSION }}
          frosty5689/mdc:${{ env.BUILD_VERSION }}
          frosty5689/mdc:${{ env.TAG_VERSION }}
          frosty5689/mdc:latest
          ghcr.io/frosty5689/mdc:${{ env.MAJOR_VERSION }}
          ghcr.io/frosty5689/mdc:${{ env.MINOR_VERSION }}
          ghcr.io/frosty5689/mdc:${{ env.BUILD_VERSION }}
          ghcr.io/frosty5689/mdc:${{ env.TAG_VERSION }}
          ghcr.io/frosty5689/mdc:latest
        build-args: |
          VERSION=${{ env.BUILD_VERSION }}
          BUILD_DATE=${{ env.BUILD_DATE }}
        cache-from: type=registry,ref=ghcr.io/frosty5689/mdc:buildcache
        cache-to: type=registry,ref=ghcr.io/frosty5689/mdc:buildcache,mode=max
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}    
