name: sync readme

on: 
  push:
    branches:
      - master
    paths:
      - "README.md"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: sync frosty5689/mdc
          uses: ms-jpq/sync-dockerhub-readme@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository: frosty5689/mdc
            readme: README.md