name: test

on: 
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".github/**"
      - "build-stage/**"
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".github/**"
      - "build-stage/**"
  workflow_dispatch:
    inputs:
      start_test:
        description: '构建测试镜像'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Set up build args
      run: |
        echo "TAG_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/frosty5689/mdc:nightly-${{ github.sha }}
        build-args: |
          VERSION=nightly-${{ github.sha }}
          BUILD_DATE=${{ env.BUILD_DATE }}

  